
project_id = "dxgscdegcjhejmqcvajc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true
port = 54327

[functions]
[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
