// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxgscdegcjhejmqcvajc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Z3NjZGVnY2poZWptcWN2YWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODc4NzYsImV4cCI6MjA1OTk2Mzg3Nn0.iW0Gev-EYC_cGWdNT1F-7QRdDn-fjIi7VG0R6EQiw8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);